apiVersion: v1
kind: Service
metadata:
  name: azure-driver
  labels:
    app: azure-driver
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 7275
    targetPort: 7275
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: http
  selector:
    app: azure-driver