{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /  # This line is only needed when deploying on IBM Cloud Private.
  name: azure-driver-ingress  # The ingress name must be unique for each ingress rule created.
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /  # This is the url path used to access the service externally.
        pathType: ImplementationSpecific
        backend:
         service:
           name: azure-driver
           port: 
             number: 7275
{{- end }}